
services:
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 7077
        published: 7077
        protocol: tcp
        mode: host
    environment:
        SPARK_MASTER_PORT: "7077"
        SPARK_MASTER_WEBUI_PORT: "8080"
        SPARK_MASTER_LOG: "/home/docker/spark-cluster/spark_stack/logs"
    networks:
      - siesta-net


  spark-worker-1:
    image: spark-worker
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    environment:
        SPARK_MASTER_PORT: "7077"
        CORES: "4"
        MEMORY: "4G"
        SPARK_WORKER_WEBUI_PORT: "8081"
        SPARK_WORKER_LOG: "/home/docker/spark-cluster/spark_stack/logs"
    networks:
      - siesta-net


  spark-worker-2:
    image: spark-worker
    ports:
      - target: 8082
        published: 8082
        protocol: tcp
        mode: host
    environment:
      SPARK_MASTER_PORT: "7077"
      CORES: "4"
      MEMORY: "4G"
      SPARK_WORKER_WEBUI_PORT: "8082"
      SPARK_WORKER_LOG: "/home/docker/spark-cluster/spark_stack/logs"
    networks:
      - siesta-net

volumes:
  spark-master-logs:
  spark-worker-1-logs:
  spark-worker-2-logs:

networks:
  siesta-net:
    name: siesta-net
    external: true